from tkinter import *

def teacherReg():
       screen1 = Toplevel(screen)
       screen.title("Teacher Registration")
       screen1.geometry("700x500")
       screen1.config(bg = "light blue")
       Label(screen1, text = "Teacher Registration", bg = "light blue", height = "2", font = ("arial",24,"bold")).pack()
       Label(screen1, bg = "light blue").pack()

       firstname = StringVar()
       lastname = StringVar()
       age = StringVar()
       dob = StringVar()
       mobile_no = StringVar()
       email_id = StringVar()
       gender = StringVar()
       branch = StringVar()
       address = StringVar()
       password = StringVar()

       Label(screen1, text = "FIRSTNAME      : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=110)
       Entry(screen1, textvariable = firstname).place(x=190,y=110)
       Label(screen1, text = "LASTNAME       : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=140)
       Entry(screen1, textvariable = lastname).place(x=190,y=140)
       Label(screen1, text = "AGE                     : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=170)
       Entry(screen1, textvariable = age).place(x=190,y=170)
       Label(screen1, text = "DOB                    : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=200)
       Entry(screen1, textvariable = dob).place(x=190,y=200)
       Label(screen1, text = "MOBILE NO      : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=230)
       Entry(screen1, textvariable = mobile_no).place(x=190,y=230)
       Label(screen1, text = "EMAIL ID           : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=260)
       Entry(screen1, textvariable = email_id).place(x=190,y=263)
       Label(screen1, text = "GENDER           : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=290)
       Radiobutton(screen1,text = "Male", bg = "light blue", padx = 5, variable=gender, value = 1).place(x=190,y=290)
       Radiobutton(screen1,text = "Female", bg = "light blue", padx = 20, variable=gender, value = 2).place(x=250,y=290)
       Label(screen1, text = "BRANCH          : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=320)
       list_branch = ['MECHANICAL','CIVIL','CSE','AI','IT','ELECTRICAL','ETC','ETRX'];
       droplist = OptionMenu(screen1,branch,*list_branch)
       droplist.config(width = 18, bg = "light blue")
       branch.set("Select Your Branch")
       droplist.place(x=190,y=315)
       Label(screen1, text = "ADDRESS        : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=350)
       Entry(screen1, textvariable = address).place(x=190,y=350)
       Label(screen1, text = "PASSWORD     : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=380)
       Entry(screen1, textvariable = password,show = "*").place(x=190,y=380)
       Button(screen1, text = "Register",width = 10, height = 1, bg = "dark blue", fg = "ghost white").place(x=180,y=420)
       Button(screen1, text = "Clear",width = 10, height = 1, bg = "dark blue", fg = "ghost white").place(x=280,y=420)


def studentReg():
       screen1 = Toplevel(screen)
       screen.title("Student Registration")
       screen1.geometry("700x500")
       screen1.config(bg = "light blue")
       Label(screen1, text = "Student Registration", bg = "light blue", height = "2", font = ("arial",24,"bold")).pack()
       Label(screen1, bg = "light blue").pack()

       firstname = StringVar()
       lastname = StringVar()
       age = StringVar()
       dob = StringVar()
       mobile_no = StringVar()
       email_id = StringVar()
       gender = StringVar()
       branch = StringVar()
       section = StringVar()
       roll_no = StringVar()
       address = StringVar()
       password = StringVar()

       Label(screen1, text = "FIRSTNAME      : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=110)
       Entry(screen1, textvariable = firstname).place(x=190,y=110)
       Label(screen1, text = "LASTNAME       : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=140)
       Entry(screen1, textvariable = lastname).place(x=190,y=140)
       Label(screen1, text = "AGE                     : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=170)
       Entry(screen1, textvariable = age).place(x=190,y=170)
       Label(screen1, text = "DOB                    : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=200)
       Entry(screen1, textvariable = dob).place(x=190,y=200)
       Label(screen1, text = "MOBILE NO      : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=230)
       Entry(screen1, textvariable = mobile_no).place(x=190,y=230)
       Label(screen1, text = "EMAIL ID           : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=260)
       Entry(screen1, textvariable = email_id).place(x=190,y=263)
       Label(screen1, text = "GENDER           : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=290)
       Radiobutton(screen1,text = "Male", bg = "light blue", padx = 5, variable=gender, value = 1).place(x=190,y=290)
       Radiobutton(screen1,text = "Female", bg = "light blue", padx = 20, variable=gender, value = 2).place(x=250,y=290)
       Label(screen1, text = "BRANCH          : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=320)
       list_branch = ['MECHANICAL','CIVIL','CSE','AI','IT','ELECTRICAL','ETC','ETRX'];
       droplist = OptionMenu(screen1,branch,*list_branch)
       droplist.config(width = 18, bg = "light blue")
       branch.set("Select Your Branch")
       droplist.place(x=190,y=315)
       Label(screen1, text = "SECTION          : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=350)
       list_section = ['A','B','C','D','E','F','G','H','I','J','K','L','M',];
       droplist = OptionMenu(screen1,section,*list_section)
       droplist.config(width = 18, bg = "light blue")
       section.set("Select Your Section")
       droplist.place(x=190,y=350)
       Label(screen1, text = "ROLL NO          : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=380)
       Entry(screen1, textvariable = roll_no).place(x=190,y=380)
       Label(screen1, text = "ADDRESS        : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=410)
       Entry(screen1, textvariable = address).place(x=190,y=410)
       Label(screen1, text = "PASSWORD       : ", bg = "light blue", font = ("arial",12,"bold")).place(x=50,y=440)
       Entry(screen1, textvariable = password, show = "*").place(x=190,y=440)
       Button(screen1, text = "Register",width = 10, height = 1, bg = "dark blue", fg = "ghost white").place(x=180,y=470)
       Button(screen1, text = "Clear",width = 10, height = 1, bg = "dark blue", fg = "ghost white").place(x=280,y=470)
       

def register():
       screen1 = Toplevel(screen)
       screen1.title("NEW REGISTRATION")
       screen1.geometry("700x500")
       screen1.config(bg = "light blue")
       Label(screen1, text = "New Registration", bg = "light blue", height = "2", font = ("arial",24,"bold")).pack()
       Label(screen1, bg = "light blue").pack()
       Button(screen1, text = "Student Registration",width = 25, height = 2,bg = "light green", command = studentReg).place(x=250,y=140)
       Label(text ="").pack()
       Button(screen1, text = "Teacher Registration",width = 25, height = 2,bg = "light green", command = teacherReg).place(x=250,y=200)
       Label(text ="").pack()
       

def login():
       screen1 = Toplevel(screen)
       screen1.title("LOGIN")
       screen1.geometry("700x500")
       screen1.config(bg = "light blue")

       username = StringVar()
       password = StringVar()
       
       Label(screen1, text = "Please Enter Login Credentials Below", bg = "light blue", height = "2", font = ("arial",12,"bold")).pack()
       Label(screen1, bg = "light blue").pack()
       Label(screen1, text = "Username : ", bg = "light blue").pack()
       Entry(screen1, textvariable = username).pack()
       Label(screen1, text = "Password : ", bg = "light blue").pack()
       Entry(screen1, textvariable = password, show ="*").pack()
       Label(screen1, bg = "light blue").pack()
       Button(screen1, text = "Login",width = 10, height = 1, bg = "dark blue", fg = "ghost white").pack()


def main_screen():
       global screen
       screen = Tk()
       screen.geometry("700x500")
       screen.title("Student Database Management System")
       screen.config(bg = "light blue")
       Label(text = "Student Database Management System", bg = "dark blue", fg = "yellow", height = "2", font = ("arial",24,"bold")).pack()
       Button(text = "Registration",height ="2", width ="30", bg = "light green", command = register).place(x=250,y=140)
       Label(bg = "light blue").pack()
       Button(text = "Login",height ="2", width ="30", bg = "light green", command = login).place(x=250,y=200)
       Label(bg = "light blue").pack()
       screen.mainloop()
main_screen()
       
